/**
 * Textos do aplicativo. O pt-BR e a fonte da verdade: o tipo Dicionario sai
 * dele, e o TypeScript reprova o `en` se faltar alguma chave.
 *
 * Convencao de interpolacao: `{nome}` no texto, trocado em tempo de render
 * (ver `preencher` e `comDestaque` em lib/idioma.tsx). Nada de concatenar
 * pedacos de frase em codigo — em ingles a ordem das palavras muda.
 */

export type Idioma = "pt-BR" | "en";

/**
 * `sigla` no lugar da bandeira: o Windows nao tem glifo para emoji de bandeira
 * (os regional indicators saem como duas letras cruas), entao a bandeira do
 * exemplo do reui apareceria como "US" solto. A sigla e proposital e renderiza
 * igual em qualquer maquina.
 */
export const IDIOMAS: { valor: Idioma; rotulo: string; sigla: string }[] = [
  { valor: "pt-BR", rotulo: "Português (Brasil)", sigla: "BR" },
  { valor: "en", rotulo: "English", sigla: "EN" },
];

const pt = {
  login: {
    convite: "Entre para desbloquear um universo de possibilidades.",
    rotuloEmail: "E-mail corporativo",
    placeholderEmail: "voce@suaempresa.com",
    ajudaEmail: "Usamos o domínio do seu e-mail para identificar a sua organização.",
    entrar: "Entrar com Microsoft",
    entrando: "Abrindo o login da Microsoft...",
    // {senha} recebe destaque em negrito
    aviso: "Você entra na página oficial da Microsoft. O app {senha} — recebe apenas uma autorização.",
    avisoSenha: "nunca vê sua senha",
    idioma: "Idioma",
  },

  carregando: {
    preparando: "Preparando o seu universo...",
  },

  reauth: {
    titulo: "Atualização de acesso necessária",
    descricao:
      "As permissões do app foram atualizadas. Entre novamente para carregar os novos recursos.",
    entrarNovamente: "Entrar novamente",
    agoraNao: "Agora não",
  },

  lockScreen: {
    titulo: "Aplicativo bloqueado",
    descricao: "Digite o seu PIN para continuar.",
    descricaoComNome: "Olá, {nome}. Digite o seu PIN para continuar.",
    rotuloPin: "PIN",
    placeholderPin: "4 a 8 dígitos",
    ajuda: "O PIN é verificado somente neste dispositivo.",
    desbloquear: "Desbloquear",
    verificando: "Verificando...",
    pinIncorreto: "PIN incorreto. {n} tentativa(s) restante(s).",
    muitasTentativas: "Muitas tentativas incorretas.",
    tenteEm: "Muitas tentativas incorretas. Tente novamente em {s}s.",
    erroValidacao: "Não foi possível verificar o PIN. Tente novamente.",
    recuperar: "Sair e entrar novamente",
    erroRecuperacao: "Não foi possível encerrar a sessão. Tente novamente.",
    statusIndisponivel:
      "Não foi possível confirmar o estado do bloqueio. O conteúdo permanece protegido.",
    tentarNovamente: "Tentar novamente",
  },

  nav: {
    organizacao: "Organização",
    plataforma: "Plataforma",
    microsoft365: "Microsoft 365",
    // Grupo da sidebar. Separado do "Microsoft 365" acima, que e a legenda da
    // organizacao no topo e continua sendo o nome da plataforma.
    galaxie: "Galaxie",
    copilot: "M365 Copilot",
    comms: "Comms",
    astro: "Astro",
    pulsar: "Pulsar",
    windows: "Windows",
    outlook: "Outlook",
    onedrive: "OneDrive",
    apps: "Apps",
    controlRoom: "Bridge",
    navegador: "Navigator",
    performance: "Performance",
    caminhosLongos: "Caminhos longos",
    configuracoes: "Configurações",
    conta: "Conta",
    // Agenda vive no rodapé do sidebar, seção separada da caixa de entrada (#50).
    agenda: "Agenda",
    irPara365: "Ir para Microsoft 365",
    sharepoint: "SharePoint",
    sair: "Sair",
    alternarMenu: "Alternar menu",
    buscarEm: "Buscar em {nome}...",
  },

  abas: {
    bibliotecas: "Bibliotecas online",
    meusArquivos: "Meus arquivos",
    problemas: "Solução de problemas",
  },

  bibliotecas: {
    titulo: "Biblioteca de documentos",
    descricao:
      "As bibliotecas de documentos organizam todo o inventário da empresa em sites do SharePoint. Use esta seção para habilitar a sincronização do seu OneDrive com as bibliotecas que você tem acesso.",
    descricaoPadrao: "Biblioteca de documentos do SharePoint.",
    rodape:
      "As bibliotecas aparecem no seu OneDrive, no Explorer. Só ocupam espaço quando você abre um arquivo.",
    carregando: "Carregando suas bibliotecas...",
    vazio: "Nenhuma biblioteca disponível para a sua conta.",
    conectado: "Conectado",
    desconectado: "Desconectado",
    semAcesso: "Sem acesso",
    abrir: "Abrir biblioteca",
    abrirExplorer: "Abrir no Explorer",
    abrirSharepoint: "Abrir no SharePoint",
    conectar: "Conectar {nome}",
    desconectar: "Desconectar {nome}",
    tamanho: "Tamanho da biblioteca",
    pastas: "{n} pastas",
    arquivos: "{n} arquivos",
    tituloPastas: "Pastas (aproximado, vem da busca do SharePoint)",
    tituloArquivos: "Arquivos (aproximado, vem da busca do SharePoint)",
    consultando: "{o} — consultando",
  },

  confirmar: {
    tituloConectar: "Antes de continuar",
    tituloDesconectar: "Remover esta biblioteca?",
    descConectar:
      "Ao habilitar {nome}, o OneDrive vai sincronizar todas as pastas e arquivos dela com a sua máquina. Eles aparecem no Explorer, mas só ocupam espaço quando você abre.",
    descDesconectar:
      "A pasta {nome} sai do seu OneDrive e do Explorer, inclusive os arquivos que você baixou para uso offline. Nada é apagado do SharePoint: a biblioteca continua lá e você pode reconectar quando quiser.",
    cartaoPastas: "Pastas",
    cartaoArquivos: "Arquivos",
    cartaoPeso: "Peso",
    pastasConectar: "Quantidade de pastas na biblioteca",
    pastasDesconectar: "Pastas que saem do seu Explorer",
    arquivosConectar: "Quantidade de arquivos na biblioteca",
    arquivosDesconectar: "Arquivos que saem do seu Explorer",
    pesoDescricao: "Tamanho da biblioteca na nuvem",
    naoPerguntar: "Não pedir confirmação novamente",
    naoPerguntarAjuda:
      "Nas próximas vezes, a biblioteca conecta direto ao ligar a chave. Dá para reativar o aviso em Configurações.",
    naoPerguntarAjudaRotulo:
      "Mais informações sobre não pedir confirmação novamente",
    continuar: "Continuar",
    depois: "Deixar pra depois",
    remover: "Remover biblioteca",
    removendo: "Removendo",
    removida: "Removida",
    cancelar: "Cancelar",
  },

  problemas: {
    titulo: "Solução de problemas",
    descricao:
      "Correções para os perrengues clássicos do OneDrive, sem precisar abrir chamado.",
    item1: "Reiniciar o OneDrive",
    item2: "Destravar a sincronização",
    item3: "Reconectar a conta do Microsoft 365",
    item4: "Liberar espaço com arquivos sob demanda",
  },

  emBreveOutlook: {
    descricao: "Ferramentas de diagnóstico do e-mail vão aparecer aqui.",
    item1: "Verificar regras e encaminhamentos",
    item2: "Tamanho da caixa e limpeza",
    item3: "Reparar perfil do Outlook",
  },

  emBrevePerformance: {
    descricao: "Diagnóstico e ajustes de desempenho da máquina.",
    item1: "Espaço em disco e arquivos temporários",
    item2: "Programas que iniciam com o Windows",
    item3: "Estado da sincronização do OneDrive",
  },

  configuracoes: {
    descricao: "Preferências do aplicativo e da sua conta.",
  },

  notificacoes: {
    titulo: "Notificações",
    subtitulo: "Escolha um som para cada tipo de aviso do Bridge.",
    emailTitulo: "E-mails recebidos",
    emailDescricao:
      "Toca uma vez quando chegam novos e-mails na sua Caixa de entrada.",
    mensagemTitulo: "Mensagens recebidas",
    mensagemDescricao: "Toca quando você recebe uma nova mensagem de chat.",
    sincronizacaoTitulo: "Problemas de sincronização",
    sincronizacaoDescricao:
      "Toca quando o Bridge encontra um erro ao sincronizar com o Microsoft 365.",
    semSom: "Não tocar nada",
    sonsDisponiveis: "Sons disponíveis",
    preview: "Preview",
  },

  templates: {
    titulo: "Templates de e-mail",
    descricao:
      "Modelos reutilizáveis para inserir no corpo de uma mensagem. Ficam guardados neste computador.",
    novo: "Novo template",
    vazio:
      "Nenhum template ainda. Crie um para reaproveitar os textos que você manda sempre.",
    nome: "Nome",
    nomePlaceholder: "Ex.: Resposta padrão de suporte",
    corpo: "Corpo",
    corpoPlaceholder: "Escreva o conteúdo do template...",
    novoTitulo: "Novo template",
    editarTitulo: "Editar template",
    salvar: "Salvar",
    cancelar: "Cancelar",
    editar: "Editar",
    excluir: "Excluir",
    excluirTitulo: "Excluir template?",
    excluirDescricao:
      "O template “{nome}” será removido deste computador. Não dá para desfazer.",
    salvo: "Template salvo",
    excluido: "Template excluído",
    inserir: "Inserir template",
    semTemplates: "Nenhum template salvo",
  },

  apps: {
    maisUsados: "Mais utilizados",
    explorar: "Explore por categoria",
    abrirAqui: "Abrir aqui",
    abrirNavegador: "Abrir no navegador padrão",
    maisOpcoes: "Mais opções",
    produtividade: "Produtividade",
    utilitarios: "Utilitários",
    educacao: "Educação",
    comunicacao: "Comunicação",
    conteudo: "Gestão de conteúdo",
    projetos: "Gestão de projetos",
    experiencia: "Experiência do funcionário",
    desenvolvimento: "Ferramentas de desenvolvimento",
    avisoSessao:
      "Os aplicativos abrem aqui dentro. Na primeira vez a Microsoft pede o seu login nesta janela; depois a sessão fica guardada.",
  },

  meusArquivos: {
    titulo: "Meus arquivos",
    descricao:
      "As pastas do seu OneDrive pessoal. Tamanho, pastas e arquivos de cada uma — para achar o que mais ocupa espaço.",
    carregando: "Carregando suas pastas...",
    vazio: "Nenhuma pasta no seu OneDrive.",
    usoTitulo: "Uso do OneDrive",
    usoLinha: "{u} de {t}",
    usado: "Usado",
    limite: "Limite",
    tiposTitulo: "Tipos de arquivo mais comuns",
    tiposNota: "Por quantidade — o Graph não informa o peso por tipo.",
    tiposUnidade: "{n} arquivos",
  },

  navegador: {
    titulo: "Navigator",
    subtitulo: "Hora de zarpar",
    buscar: "Buscar apps ou traçar uma rota...",
    vazio: "Nada por aqui.",
    navegar: "Traçar rota",
    irPara: "Ir para {nome}",
    pesquisar: "Pesquisar “{q}” na web",
    novaAba: "Nova aba",
    fecharAba: "Fechar aba",
    fecharOutras: "Fechar as outras abas",
    abas: "Abas do Navigator",
    dormindoClique: "{nome}: dormindo — clique para reativar",
    fixadaNome: "{nome}: aba fixada",
    dormindoTotal: "{n} dormindo",
    reativando: "Reativando…",
    fixarAba: "Fixar aba",
    desafixarAba: "Desafixar aba",
    manterAcordada: "Manter acordada",
    manterAcordadaAtivo: "Mantida acordada",
    permitirDormir: "Permitir suspensão automática",
    colocarDormir: "Colocar para dormir",
    dormirOutras: "Suspender as outras",
    paleta: "Paleta de comandos",
    paletaTitulo: "Paleta de comandos",
    paletaDescricao:
      "Busque abas, aplicativos e ações, ou trace uma rota.",
    paletaBuscar:
      "Abas, apps, ações… ou trace uma rota  ( > ações · @ abas · # histórico )",
    grupoAcoes: "Ações",
    grupoAbas: "Abas abertas",
    grupoHistorico: "Histórico",
    historicoEmBreve: "O histórico chega em breve.",
    grupoMaisAcessados: "Mais acessados",
    historicoTitulo: "Histórico",
    historicoBuscar: "Buscar no histórico…",
    historicoVazio: "Nenhuma página no histórico ainda.",
    limparHistorico: "Limpar histórico",
    limparUltimaHora: "Última hora",
    limparHoje: "Hoje",
    limparTudo: "Tudo",
    modoPrivado: "Modo privado",
    modoPrivadoAtivo: "Navegação privada",
    abaPrivada: "{nome}: aba privada",
    abaAtual: "Atual",
    dormindo: "Dormindo",
    grupoNovo: "Novo grupo",
    grupoAdicionarA: "Adicionar ao grupo",
    grupoRemoverDe: "Remover do grupo",
    grupoRecolher: "Recolher grupo",
    grupoExpandir: "Expandir grupo",
    grupoEditar: "Editar grupo",
    grupoExcluir: "Excluir grupo",
    grupoNomeLabel: "Nome",
    grupoCorLabel: "Cor",
    grupoSalvar: "Salvar",
    grupoCancelar: "Cancelar",
    grupoNomePadrao: "Grupo",
    grupoNomePlaceholder: "Nome do grupo",
    grupoReordenar: "Arrastar para reordenar",
    grupoAria: "{nome}: grupo de abas ({n})",
    corRosa: "Rosa",
    corVioleta: "Violeta",
    corVerde: "Verde",
    corAmbar: "Âmbar",
    corVermelho: "Vermelho",
    grupoFavoritos: "Favoritos",
    favoritosBarra: "Barra de favoritos",
    favMenu: "Favoritos",
    favAdicionarAba: "Adicionar aba atual",
    favNovaPasta: "Nova pasta",
    favImportar: "Importar do Chrome/Edge",
    favImportarDica: "Importe seus favoritos do Chrome ou Edge",
    favAbrir: "Abrir",
    favRenomear: "Renomear",
    favRemover: "Remover",
    favNomeLabel: "Nome",
    favSalvar: "Salvar",
    favCancelar: "Cancelar",
    favPastaNomePadrao: "Nova pasta",
    favRenomearTitulo: "Renomear favorito",
    importarTitulo: "Importar favoritos",
    importarDescricao: "Escolha os favoritos do Chrome/Edge para trazer.",
    importarCarregando: "Procurando favoritos…",
    importarVazio: "Nenhum favorito encontrado. Chrome ou Edge não detectados.",
    importarBloqueado:
      "Não conseguimos ler os favoritos do Chrome/Edge — o acesso pode estar bloqueado pelo seu antivírus ou política de segurança. Importe por um arquivo exportado do navegador:",
    importarSemFavoritos: "Nenhum favorito encontrado no Chrome/Edge.",
    importarArquivo: "Importar de arquivo HTML…",
    importarArquivoDica:
      "No Chrome/Edge: Favoritos → Gerenciar favoritos → ⋯ → Exportar favoritos.",
    importarSelecionarTudo: "Selecionar tudo",
    importarLimpar: "Limpar",
    importarContagem: "{n} de {total} selecionados",
    importarPerfil: "{navegador} · {perfil}",
    importarAplicar: "Importar {n}",
    importarNada: "Nada selecionado",
  },

  // Controles de janela (barra-janela.tsx). Só existem dentro do Tauri.
  janela: {
    minimizar: "Minimizar",
    maximizar: "Maximizar",
    restaurar: "Restaurar",
    fechar: "Fechar",
  },

  atualizacao: {
    titulo: "Atualização disponível!",
    versao: "Versão {v} ({d})",
    descricao:
      "Uma nova versão do aplicativo está pronta. Ao atualizar agora, o app reinicia e volta com as últimas correções.",
    baixando: "Baixando a atualização... {p}%",
    agora: "Atualizar agora",
    atualizando: "Atualizando",
    depois: "Lembrar depois",
  },

  controlRoom: {
    saudacao: "Olá, {nome}",
    subtitulo: "Seu dia em um olhar.",
    hoje: "Hoje",
    // Cliente de e-mail
    novoEmail: "Novo e-mail",
    composeOutlook: "Escrever no Outlook",
    composerEmBreve: "Compositor no app chega em breve — use \"Escrever no Outlook\".",
    grupoMail: "E-mail",
    grupoOutras: "Pastas",
    pastaInbox: "Caixa de entrada",
    pastaDrafts: "Rascunhos",
    pastaSent: "Enviados",
    pastaArchive: "Arquivo",
    pastaJunk: "Lixo eletrônico",
    pastaTrash: "Itens excluídos",
    abaAnexos: "Com anexos",
    semMensagens: "Nenhuma mensagem nesta pasta.",
    semMensagensTitulo: "Caixa limpa",
    semResultados: "Nenhum resultado.",
    escolhaEmail: "Escolha um e-mail para ver os detalhes.",
    ccLabel: "Cc",
    semEventosTitulo: "Sem eventos",
    agendaErroTitulo: "Não foi possível carregar a agenda",
    agendaErroDica: "Falha momentânea na conexão. Tente atualizar.",
    atualizar: "Atualizar",
    tentarNovamente: "Tentar novamente",
    // Ações de e-mail
    excluir: "Excluir",
    sinalizar: "Sinalizar",
    marcarNaoLido: "Marcar como não lido",
    marcarLido: "Marcar como lido",
    removerSinal: "Remover sinalização",
    excluirPermanente: "Excluir permanentemente",
    esvaziarLixeira: "Esvaziar lixeira",
    emailExcluido: "E-mail excluído.",
    erroAcao: "Não consegui completar a ação.",
    // Menu de contexto de PASTA (#89)
    marcarTodasLidas: "Marcar todas como lidas",
    esvaziarPasta: "Esvaziar pasta",
    marcandoTodasLidas: "Marcando todas como lidas…",
    todasMarcadasLidas: "{n} marcadas como lidas.",
    nenhumaNaoLida: "Nenhuma mensagem não lida nesta pasta.",
    esvaziandoPasta: "Esvaziando a pasta…",
    pastaEsvaziada: "Pasta esvaziada ({n}).",
    esvaziarPastaTitulo: "Esvaziar “{pasta}”?",
    esvaziarPastaDesc:
      "Todas as mensagens desta pasta serão apagadas. Esta ação não pode ser desfeita.",
    esvaziarPastaConfirmar: "Esvaziar",
    // Mover para pasta (submenu do menu de contexto, #88)
    moverPara: "Mover para pasta…",
    moverBuscarPasta: "Buscar pasta…",
    moverSemPastas: "Nenhuma pasta encontrada.",
    moverCarregandoPastas: "Carregando pastas…",
    emailMovido: "E-mail movido para {pasta}.",
    selecionadosMovidos: "{n} e-mails movidos para {pasta}.",
    // CRUD de subpastas (#90)
    criarSubpasta: "Criar subpasta",
    renomearPasta: "Renomear",
    excluirPasta: "Excluir pasta",
    moverPasta: "Mover pasta…",
    criarSubpastaTitulo: "Nova subpasta em “{pasta}”",
    criarSubpastaDesc: "Digite o nome da subpasta.",
    renomearPastaTitulo: "Renomear “{pasta}”",
    renomearPastaDesc: "Digite o novo nome da pasta.",
    nomePastaRotulo: "Nome da pasta",
    nomePastaPlaceholder: "Ex.: Clientes",
    nomePastaVazio: "Digite um nome para a pasta.",
    nomePastaDuplicado: "Já existe uma pasta com esse nome aqui.",
    criar: "Criar",
    salvar: "Salvar",
    criandoSubpasta: "Criando a subpasta…",
    subpastaCriada: "Subpasta “{pasta}” criada.",
    renomeandoPasta: "Renomeando a pasta…",
    pastaRenomeada: "Pasta renomeada para “{pasta}”.",
    excluirPastaTitulo: "Excluir “{pasta}”?",
    excluirPastaDesc:
      "A pasta e todo o conteúdo vão para a Lixeira. Você pode recuperar de lá.",
    excluirPastaConfirmar: "Excluir",
    excluindoPasta: "Excluindo a pasta…",
    pastaExcluida: "Pasta “{pasta}” movida para a Lixeira.",
    pastaExcluidaDefinitiva: "Pasta “{pasta}” excluída definitivamente.",
    movendoPasta: "Movendo a pasta…",
    pastaMovida: "Pasta movida para {pasta}.",
    // Toasts
    enviadoDescricao: "Sua mensagem foi entregue.",
    envioPendente: "Enviando em {n}s",
    envioPendenteDescricao: "A mensagem está aguardando no Outbox.",
    desfazerEnvio: "Desfazer",
    envioCancelado: "Envio cancelado",
    enviandoAgora: "Enviando mensagem…",
    flagAdicionada: "E-mail sinalizado",
    flagRemovida: "Sinalização removida",
    downloadTitulo: "Download concluído",
    baixandoAnexo: "Baixando anexo...",
    abrirArquivo: "Abrir",
    abrirPasta: "Abrir pasta",
    expandirPasta: "Expandir {pasta}",
    recolherPasta: "Recolher {pasta}",
    dispensar: "Dispensar",
    novoEmailRecebido: "Novo e-mail",
    nSelecionados: "{n} selecionados",
    excluirSelecionados: "Excluir selecionados",
    excluindo: "Excluindo…",
    excluidos: "Excluídos",
    mensagemOriginal: "Mensagem original",
    ordenarPor: "Ordenar por",
    ordenaData: "Data",
    ordenaRemetente: "Remetente",
    ordenaAssunto: "Assunto",
    ordenaTamanho: "Tamanho",
    ordenaImportancia: "Importância",
    ordenaFlag: "Sinalização",
    ordemDecrescente: "Decrescente",
    ordemCrescente: "Crescente",
    // Preferências de leitura (#95) — quando marcar a mensagem aberta como lida.
    // Namespace próprio (pref*) pra não colidir com as AÇÕES marcarLido/marcarNaoLido.
    prefLeitura: "Preferências de leitura",
    prefMarcarLidoTitulo: "Marcar como lido",
    prefMarcarLidoImediato: "Ao abrir",
    prefMarcarLidoAtraso: "Após {n} segundos",
    prefMarcarLidoManual: "Somente manualmente",
    grupoFlagged: "Sinalizados",
    grupoHoje: "Hoje",
    grupoOntem: "Ontem",
    grupo7dias: "Últimos 7 dias",
    grupo30dias: "Últimos 30 dias",
    grupoAntigos: "Mais antigos",
    expandirConversa: "Expandir conversa",
    recolherConversa: "Recolher conversa",
    expandirConversaContagem: "Expandir conversa ({n} mensagens)",
    nMensagensConversa: "{n} mensagens nesta conversa",
    limparSelecao: "Limpar seleção",
    selecionarTudo: "Selecionar tudo",
    selecionadosExcluidos: "{n} e-mails excluídos.",
    conversaSelecionada: "1 conversa selecionada",
    conversasSelecionadas: "{n} conversas selecionadas",
    multiSelecaoDica: "Del exclui as selecionadas · Ctrl+A seleciona todas · Esc desfaz · ? mostra os atalhos.",
    // Compose (modal nova mensagem + reply/forward)
    novaMensagem: "Nova mensagem",
    ccoLabel: "Cco",
    assunto: "Assunto",
    assuntoPlaceholder: "Assunto",
    corpoPlaceholder: "Escreva sua mensagem...",
    mostrarCcCco: "Cc/Cco",
    contatosSalvos: "{n} contatos salvos.",
    // Autocomplete de destinatários (#40)
    destinatariosPlaceholder: "Adicionar destinatários...",
    secaoSeusContatos: "Seus contatos",
    secaoOrganizacao: "De sua organização",
    secaoDigitado: "Usar o endereço digitado",
    semContatos: "Nenhum contato encontrado.",
    buscandoContatos: "Buscando contatos...",
    removerDestinatario: "Remover {nome}",
    // Menção @ no corpo (#106)
    semDestinatariosMencao: "Adicione destinatários em Para/Cc/Cco para mencionar.",
    // Agenda / Up Next
    upNext: "A seguir",
    semEventos: "Nada na agenda neste dia.",
    agendaBuscar: "Buscar eventos...",
    online: "Online",
    diaInteiro: "Dia inteiro",
    mailboxTitulo: "Caixa de correio",
    agendaTitulo: "Agenda",
    // Subtítulos do header do Bridge por módulo (#231)
    mailboxSubtitulo: "Suas mensagens em um olhar.",
    peopleSubtitulo: "Seus contatos do Microsoft 365.",
    agendaSubtitulo: "Seus próximos compromissos.",
    // Agenda — calendário completo (#211)
    agendaNovoEvento: "Novo evento",
    agendaHoje: "Hoje",
    agendaViewMes: "Mês",
    agendaViewSemana: "Semana",
    agendaViewDia: "Dia",
    agendaViewAgenda: "Agenda",
    agendaCalSemEventos: "Sem eventos",
    agendaCalCarregando: "Carregando eventos",
    agendaCalMais: "mais",
    agendaEditar: "Editar",
    agendaExcluir: "Excluir",
    agendaFormCriarTitulo: "Novo evento",
    agendaFormEditarTitulo: "Editar evento",
    agendaFormTitulo: "Título",
    agendaFormTituloPlaceholder: "Adicione um título",
    agendaFormDiaInteiro: "Dia inteiro",
    agendaFormInicio: "Início",
    agendaFormFim: "Fim",
    agendaFormLocal: "Local",
    agendaFormCategoria: "Categoria",
    agendaFormSemCategoria: "Nenhuma",
    agendaFormSalvar: "Salvar",
    agendaFormCriar: "Criar",
    agendaFormCancelar: "Cancelar",
    agendaTituloObrigatorio: "Informe um título para o evento.",
    agendaCriado: "Evento criado.",
    agendaAtualizado: "Evento atualizado.",
    agendaExcluido: "Evento excluído.",
    agendaErroSalvar: "Não foi possível salvar o evento.",
    agendaErroExcluir: "Não foi possível excluir o evento.",
    agendaFormConvidados: "Convidados",
    agendaFormConvidadosPlaceholder: "Adicione convidados",
    agendaFormTeams: "Reunião do Teams",
    agendaFormNovaCategoria: "Nova categoria",
    agendaFormNovaCategoriaNome: "Nome da categoria",
    agendaFormCriarCategoria: "Criar",
    agendaCategoriaCriada: "Categoria criada.",
    agendaCategoriaErro: "Não foi possível criar a categoria.",
    // Seletor de calendários (#233)
    agendaCalendarios: "Calendários",
    agendaCalendariosTodos: "Todos os calendários",
    agendaCalendariosNenhum: "Nenhum calendário",
    agendaCalendariosContagem: "{n} calendários",
    agendaCalendariosVazio: "Nenhum calendário encontrado.",
    agendaCalendariosErro: "Não foi possível carregar os calendários.",
    agendaCalendariosCarregando: "Carregando calendários",
    agendaFormCalendario: "Calendário",
    peopleTitulo: "Contatos",
    peopleDescricao: "Seus contatos e pessoas relevantes do Microsoft 365.",
    peopleContactsTab: "Pessoas",
    peopleOrganizationsTab: "Organizações",
    orgsDescricao: "Agrupe contatos por domínio e mantenha ajustes manuais.",
    orgsBuscar: "Buscar organizações...",
    orgsNova: "Nova organização",
    orgsVazia: "Nenhuma organização ainda",
    orgsVaziaDesc: "Crie uma organização para agrupar seus contatos.",
    orgsSelecionar: "Selecione uma organização",
    orgsSelecionarDesc: "Veja membros, domínios e detalhes da organização.",
    orgsMembros: "{n} membros",
    orgsAtribuir: "Atribuir contatos",
    orgsEditar: "Editar organização",
    orgsAbrirSite: "Abrir site",
    orgsDetalhes: "Detalhes",
    orgsDominios: "Domínios",
    orgsDominiosTooltip:
      "Opcional — Pessoas com os domínios indicados aqui serão adicionadas automaticamente a esta organização. Pressione Enter ou ; para informar mais de um domínio. Deixe em branco para não atrelar domínios a essa organização.",
    orgsWebsite: "Website",
    orgsNotas: "Notas",
    orgsSemDado: "Não informado",
    orgsRemoverMembro: "Remover da organização",
    orgsCriarTitulo: "Criar organização",
    orgsEditarTitulo: "Editar organização",
    orgsNome: "Nome",
    orgsNomePlaceholder: "Ex.: Galaxie Works",
    orgsDominiosPlaceholder: "galaxie.works, exemplo.com",
    orgsDominiosAjuda:
      "Separe domínios por vírgula ou Enter. Deixe vazio para uma lista manual.",
    orgsCancelar: "Cancelar",
    orgsSalvar: "Salvar",
    orgsCriar: "Criar organização",
    orgsErroCampos: "Informe um nome.",
    orgsAtribuirTitulo: "Atribuir contatos a {nome}",
    orgsBuscarContatos: "Buscar contatos...",
    orgsConfirmarAtribuicao: "Salvar atribuições",
    orgsAtribuirContato: "Atribuir à organização",
    orgsSemOrganizacoes: "Crie uma organização primeiro.",
    orgsCriada: "Organização criada.",
    orgsAtualizada: "Organização atualizada.",
    orgsAtribuicoesSalvas: "Atribuições salvas.",
    orgsRedimensionar: "Redimensionar lista e detalhe da organização",
    peopleBulkSelecionados: "{n} selecionados",
    peopleBulkLimpar: "Limpar seleção",
    peopleBulkAcoes: "Ações em massa",
    peopleBulkAtribuirOrg: "Atribuir a organização",
    bulkOrgTitulo: "Atribuir {n} contatos a uma organização",
    bulkOrgDescricao:
      "Escolha uma organização existente ou crie uma nova. A atribuição é aditiva e não remove ninguém.",
    bulkOrgBuscar: "Buscar organização...",
    bulkOrgSemOrgs: "Nenhuma organização ainda.",
    bulkOrgCriarNova: "Criar nova organização…",
    bulkOrgVoltar: "Voltar",
    bulkOrgCriarContinuar: "Criar e continuar",
    bulkOrgConfirmar: "Confirmar atribuição",
    bulkOrgPreviewAlvo: "Atribuir a {nome}",
    bulkOrgPreviewAdicionados: "serão adicionados",
    bulkOrgPreviewJaPertencem: "já pertencem (sem mudança)",
    bulkOrgPreviewSemEmail: "sem e-mail entram como membro explícito",
    bulkOrgSucesso: "{n} contatos atribuídos a {nome}.",
    peopleBuscar: "Buscar por nome, e-mail ou empresa...",
    peopleOrdenar: "Ordenar contatos",
    peopleRelevancia: "Relevância",
    peopleAZ: "Nome (A–Z)",
    peopleNome: "Nome",
    peopleEmpresa: "Empresa",
    peopleCargo: "Cargo",
    peopleEmail: "E-mail",
    peopleTelefone: "Telefone",
    peopleOrg: "Organização",
    peopleExterno: "Externo",
    peopleFrequente: "Frequente",
    peopleContatos: "Contatos",
    peopleVoltar: "Voltar aos contatos",
    peopleSelecionar: "Selecione um contato",
    peopleSelecionarDesc: "Escolha uma pessoa na lista para ver os detalhes.",
    peopleVazio: "Nenhum contato encontrado",
    peopleVazioDesc:
      "Seus contatos do Outlook aparecerão aqui conforme você troca e-mails.",
    peopleSemResultado: "Nenhum contato corresponde à busca.",
    peopleLimparBusca: "Limpar busca",
    peopleErro: "Não foi possível atualizar todos os contatos.",
    peopleTentarNovamente: "Tentar novamente",
    peopleSemPermissao: "Acesso ao People necessário",
    peopleSemPermissaoDesc:
      "Autorize {escopos} para carregar seus contatos. O login só abre quando você confirmar.",
    peopleConcederAcesso: "Conceder acesso",
    peopleCompor: "Escrever e-mail",
    peopleVerModulo: "Ver em Pessoas",
    peopleEmails: "E-mails",
    peopleTelefones: "Telefones",
    peopleEmpresaCargo: "Empresa e cargo",
    peopleSemDado: "Não informado",
    peopleEnrich: "Enriquecer",
    peopleEnrichPrompt: "Enriquecer este contato",
    peopleEnrichPromptDesc:
      "Há campos vazios que podem ser preenchidos com dados do People e do diretório.",
    peopleEnriching: "Enriquecendo…",
    peopleEnrichPreview: "Revisar adições",
    peopleEnrichPreviewDesc:
      "Escolha exatamente quais campos serão aplicados. Nada foi gravado ainda.",
    peopleEnrichApply: "Aplicar",
    peopleEnrichSessionApply: "Aplicar nesta sessão",
    peopleEnrichCancel: "Cancelar",
    peopleEnrichNoChanges: "Nenhum dado novo foi encontrado para este contato.",
    peopleEnrichSourceError: "Uma fonte não respondeu",
    peopleEnrichReadOnly: "Somente nesta sessão",
    peopleEnrichReadOnlyDesc:
      "O login atual precisa de Contacts.ReadWrite para salvar. O app não vai pedir nem tentar gravar sem sua ação.",
    peopleEnrichCopy: "Copiar dados",
    peopleEnrichCopied: "Dados copiados",
    peopleEnrichSaved: "Contato enriquecido",
    peopleEnrichSessionSaved: "Dados aplicados somente nesta sessão",
    peopleEnrichError: "Não foi possível enriquecer este contato.",
    peopleSourceContacts: "Contacts",
    peopleSourcePeople: "People",
    peopleSourceDirectory: "Diretório",
    peopleFilterSourceContacts: "Contatos salvos",
    peopleFilterSourcePeople: "Pessoas relevantes",
    peopleFilterSourceDirectory: "Diretório da organização",
    peopleSource: "Origem",
    peopleRelationship: "Relação",
    peopleHasPhone: "Tem telefone",
    peopleYes: "Sim",
    peopleNo: "Não",
    peopleFilters: "Filtros",
    peopleClearFilters: "Limpar filtros",
    peopleColumns: "Colunas",
    peopleTableView: "Visualização em tabela",
    peopleCardsView: "Visualização em cards",
    peopleRowActions: "Ações do contato",
    peopleCopyEmail: "Copiar e-mail",
    peopleEmailCopied: "E-mail copiado",
    peopleLoadMore: "Carregar mais",
    peopleDepartment: "Departamento",
    peopleOfficeLocation: "Local do escritório",
    peopleManager: "Gestor",
    peopleFieldBusinessPhone: "Telefone comercial",
    peopleFieldMobilePhone: "Celular",
    peopleFieldPhoto: "Foto",
    peopleEdit: "Editar contato",
    peopleSave: "Salvar",
    peopleSaving: "Salvando…",
    peopleEditUnavailable: "Edição indisponível",
    peopleEditUnavailableDesc:
      "Não foi possível editar este contato agora.",
    peopleEditDirectoryTitle: "Este não é um contato salvo",
    peopleEditDirectoryDesc:
      "Esta pessoa ainda não está salva nos seus contatos. Por isso, não é possível editá-la aqui.",
    peopleEditDirectoryTooltip:
      "As informações de usuários da sua organização só podem ser alteradas por um administrador.",
    peopleEditError: "Não foi possível salvar. Os valores anteriores foram restaurados.",
    peopleInvalidEmail: "Revise os endereços de e-mail.",
    peopleInvalidPhone: "Revise os números de telefone.",
    peopleInteractions: "Interações recentes",
    peopleInteractionsEmpty: "Nenhuma mensagem recente com este contato.",
    peopleInteractionsError: "Não foi possível carregar as interações.",
    peopleInbound: "Recebido",
    peopleOutbound: "Enviado",
    peopleEnrichAll: "Enriquecer todos",
    peopleEnrichSelected: "Enriquecer selecionados",
    peopleBulkTitle: "Revisão de enriquecimento",
    peopleBulkContact: "Contato {atual} de {total}",
    peopleBulkSkip: "Pular",
    peopleBulkDone: "Revisão concluída",
    colapsar: "Colapsar",
    badgeMeeting: "Reunião",
    badgeEvent: "Evento",
    convidados: "{n} convidados",
    umConvidado: "1 convidado",
    arquivos: "{n} arquivos",
    umArquivo: "1 arquivo",
    // Inbox do dia
    inbox: "Caixa de entrada",
    semEmailsDia: "Nenhum e-mail neste dia.",
    buscarEmail: "Buscar e-mails...",
    abaTodos: "Todos",
    abaNaoLidos: "Não lidos",
    abaSinalizados: "Sinalizados",
    filtroLabel: "Filtro",
    filtroToMe: "Para mim",
    filtroMentions: "Me mencionam",
    filtroInvites: "Convites de agenda",
    // Rótulos do filter-builder reui (#31): campos combináveis com E (AND).
    filtroDe: "De",
    filtroDePlaceholder: "Remetente...",
    filtroStatus: "Status",
    filtroLidos: "Lidos",
    filtroSim: "Sim",
    filtroNao: "Não",
    filtroEscopo: "Escopo",
    filtroBuscarCampo: "Buscar campo...",
    filtroLimpar: "Limpar",
    // Grupos de campos do builder (espelham "Basic"/"Select" do exemplo reui).
    filtroGrupoBasico: "Básico",
    filtroGrupoSelecao: "Seleção",
    // Operadores expostos nos chips.
    filtroOperadorIs: "é",
    filtroOpNaoE: "não é",
    filtroOpContem: "contém",
    filtroOpNaoContem: "não contém",
    filtroSelecione: "Selecione...",
    // Filtro de intervalo de datas (#110): campo "Data" com DateSelector no modal.
    filtroData: "Data",
    filtroDataSelecione: "Selecionar data",
    filtroDataTitulo: "Filtrar por data",
    filtroDataDescricao:
      "Escolha um período para filtrar as mensagens por data.",
    filtroDataDica: "Ex.: 2025, Q4, 05/10/2025",
    filtroAplicar: "Aplicar",
    // Detalhe do evento
    organizador: "Organizador",
    local: "Local",
    convidadosTitulo: "Convidados",
    entrarReuniao: "Entrar na reunião",
    // Detalhe do e-mail
    para: "Para",
    anexosTitulo: "Anexos",
    responder: "Responder",
    encaminhar: "Encaminhar",
    // Atalhos de teclado (#28) — catálogo do modal de ajuda ("?"). Chaves
    // PLANAS (o dicionário `en` exige string em cada folha de cada seção).
    atalhosTitulo: "Atalhos de teclado",
    atalhosDescricao: "Opere o Bridge sem o mouse.",
    atalhosCatNavegacao: "Navegação",
    atalhosCatSelecao: "Seleção",
    atalhosCatAcoes: "Ações",
    atalhosCatGeral: "Geral",
    atalhosNavegar: "Navegar entre mensagens",
    atalhosBuscar: "Buscar",
    atalhosSelecionarTudo: "Selecionar tudo",
    atalhosIntervalo: "Selecionar intervalo",
    atalhosCliqueIntervalo: "Shift + clique",
    atalhosMarcarItem: "Marcar/desmarcar mensagem",
    atalhosLimpar: "Limpar seleção / busca",
    atalhosResponder: "Responder",
    atalhosResponderTodos: "Responder a todos",
    atalhosEncaminhar: "Encaminhar",
    atalhosCompor: "Nova mensagem",
    atalhosLidoNaoLido: "Marcar como lido/não lido",
    atalhosSinalizar: "Sinalizar",
    atalhosExcluir: "Excluir",
    atalhosAjuda: "Mostrar esta ajuda",
    abrirOutlook: "Abrir no Outlook",
    semCorpo: "(sem conteúdo)",
    conteudoAparado: "Mostrar conteúdo aparado",
    zoomResetar: "Restaurar zoom (Ctrl+0)",
    // Segurança do leitor (#91)
    segLinkTitulo: "Abrir link externo?",
    segLinkDescricao: "Confira o destino real antes de abrir.",
    segLinkDestino: "Destino real",
    segLinkTexto: "Texto do link",
    segLinkAbrir: "Abrir mesmo assim",
    segLinkCancelar: "Cancelar",
    segLinkSuspeito: "Link suspeito",
    segLinkVerificado: "Nenhum sinal de risco detectado.",
    segAvisoMismatch: "O texto do link aparenta um site diferente do destino real.",
    segAvisoEncurtador: "Encurtador de URL — o destino final fica escondido.",
    segAvisoIp: "O link aponta para um endereço IP, não um domínio.",
    segAvisoPunycode: "Domínio com caracteres internacionais (risco de imitação).",
    segAvisoInseguro: "Conexão não segura (HTTP).",
    segAvisoRedirecionamento: "O link embute um redirecionamento para outro endereço.",
    segAutAutenticado: "Autenticado",
    segAutParcial: "Parcial",
    segAutFalhou: "Falha de autenticação",
    segAutIndisponivel: "Sem dados",
    segAutTooltipAutenticado:
      "Remetente verificado — este e-mail passou nas checagens de autenticação (SPF, DKIM e DMARC).",
    segAutTooltipParcial:
      "Autenticação parcial — parte das checagens não passou. Confira o remetente antes de confiar.",
    segAutTooltipFalhou:
      "Falha de autenticação — este e-mail pode não ser de quem diz ser. Cuidado com links e anexos.",
    segAutTooltipIndisponivel: "Sem dados de autenticação para este e-mail.",
    segAutDetalhesTecnicos: "Detalhes técnicos",
    segReplyToTitulo: "As respostas vão para outro endereço",
    segReplyToDescricao:
      "Ao responder, sua mensagem vai para {enderecos}, e não para o remetente ({de}). Isso é comum em phishing — confirme antes de responder.",
    // Compose / envio
    responderTodos: "Responder a todos",
    paraPlaceholder: "Para (separe por vírgula)",
    responderPlaceholder: "Escreva sua resposta...",
    encaminharPlaceholder: "Escreva uma mensagem...",
    enviarDe: "Enviar de",
    enviar: "Enviar",
    cancelar: "Cancelar",
    enviado: "E-mail enviado.",
    erroEnvio: "Não consegui enviar o e-mail.",
    escrevaAlgo: "Escreva a mensagem antes de enviar.",
    informeDestino: "Informe ao menos um destinatário.",
    // Insights do remetente (#94)
    insightsTitulo: "Insights do remetente",
    insightsAbrir: "Ver insights de {nome}",
    insightsErro: "Não foi possível carregar os insights.",
    insightsTentar: "Tentar de novo",
    insightsPrimeiroContato: "Primeiro e-mail com este remetente.",
    insightsRecebidos: "Recebidos",
    insightsEnviados: "Enviados",
    insightsPrimeiro: "Primeiro contato",
    insightsUltimo: "Último contato",
    insightsFrequencia: "Frequência",
    insightsPorMes: "~{n}/mês",
    // Caixas compartilhadas (#111)
    caixaMinha: "Minha caixa",
    caixaSeletor: "Caixa ativa",
    caixaAdicionarItem: "Adicionar caixa…",
    caixaDialogTitulo: "Adicionar caixa compartilhada",
    caixaDialogDesc: "Digite o endereço da caixa compartilhada que você quer acessar.",
    caixaEnderecoRotulo: "Endereço de e-mail",
    caixaEnderecoPlaceholder: "Ex.: financeiro@empresa.com",
    caixaEnderecoInvalido: "Digite um endereço de e-mail válido.",
    caixaJaAdicionada: "Essa caixa já está no seletor.",
    caixaValidando: "Validando acesso…",
    caixaAdicionarConfirmar: "Adicionar",
    caixaAdicionada: "Caixa {addr} adicionada.",
    caixaSemAcesso: "Você não tem acesso a essa caixa.",
    caixaNaoEncontrada: "Endereço não encontrado.",
    caixaErro: "Não consegui validar a caixa.",
    caixaRelogin: "Faça login novamente para acessar caixas compartilhadas.",
    caixaCompartilhadaTitulo: "Caixa compartilhada",
    caixaCompartilhadaDesc: "Leitura e gerenciamento de mensagens habilitados.",
    caixaSomenteLeitura: "Somente leitura — disponível na caixa pessoal",
    caixaSemPermissaoEscrita:
      "Você não tem permissão para alterar esta caixa compartilhada.",
    caixaSemPermissaoEnvio:
      "Você não tem permissão para enviar usando esta caixa compartilhada.",
    caixaEnvioRelogin:
      "Faça login novamente para enviar usando caixas compartilhadas.",
    caixaAcessoParcial:
      "Acesso parcial — você não tem permissão para abrir esta pasta.",
  },
  emBreveControlRoom: {
    descricao: "O painel de controle da Galaxie — sua visão geral. Em breve.",
  },
  emBreveComms: {
    descricao: "Comunicação rápida entre a equipe. Em breve.",
  },
  emBreveAstro: {
    descricao: "O chatbot da Galaxie vai morar aqui. Em breve.",
  },
  emBrevePulsar: {
    descricao: "Central de notificações e alertas — cada pulso, um aviso.",
  },

  caminhosLongos: {
    titulo: "Caminhos longos",
    descricao:
      "Por padrão o Windows trava em 260 caracteres de caminho. Pastas de projeto muito aninhadas passam disso e o arquivo simplesmente não abre — nem pelo Explorer, nem pelos aplicativos.",
    verificando: "verificando",
    ativado: "Ativado",
    desativado: "Desativado",
    aviso:
      "A alteração é feita no registro do Windows e vale para o computador inteiro, por isso o Windows vai pedir sua confirmação de administrador. Alguns programas só reconhecem a mudança depois de reiniciar.",
    nadaAFazer: "Nada a fazer — este computador já aceita caminhos longos.",
    ativar: "Ativar caminhos longos",
    aplicando: "Aplicando...",
  },

  tema: {
    alternar: "Alternar tema claro e escuro",
  },

  // Fallback do ErrorBoundary raiz (#148): mostrado quando um render estoura, no
  // lugar da tela branca.
  erro: {
    titulo: "Algo deu errado",
    descricao:
      "O aplicativo encontrou um erro inesperado. Você pode recarregar para tentar novamente.",
    recarregar: "Recarregar",
    detalhes: "Detalhes técnicos",
  },
} as const;

export type Dicionario = typeof pt;

/** Estrutura identica ao pt: o TypeScript reprova chave faltando ou sobrando. */
const en: { [K in keyof Dicionario]: { [C in keyof Dicionario[K]]: string } } = {
  login: {
    convite: "Sign in to unlock a universe of possibilities.",
    rotuloEmail: "Work email",
    placeholderEmail: "you@yourcompany.com",
    ajudaEmail: "We use your email domain to identify your organization.",
    entrar: "Sign in with Microsoft",
    entrando: "Opening the Microsoft sign-in...",
    aviso:
      "You sign in on Microsoft's official page. This app {senha} — it only receives an authorization.",
    avisoSenha: "never sees your password",
    idioma: "Language",
  },

  carregando: {
    preparando: "Getting your universe ready...",
  },

  reauth: {
    titulo: "Access update required",
    descricao:
      "The app permissions were updated. Sign in again to load the new features.",
    entrarNovamente: "Sign in again",
    agoraNao: "Not now",
  },

  lockScreen: {
    titulo: "App locked",
    descricao: "Enter your PIN to continue.",
    descricaoComNome: "Hello, {nome}. Enter your PIN to continue.",
    rotuloPin: "PIN",
    placeholderPin: "4 to 8 digits",
    ajuda: "Your PIN is verified only on this device.",
    desbloquear: "Unlock",
    verificando: "Checking...",
    pinIncorreto: "Incorrect PIN. {n} attempt(s) remaining.",
    muitasTentativas: "Too many incorrect attempts.",
    tenteEm: "Too many incorrect attempts. Try again in {s}s.",
    erroValidacao: "We couldn't verify the PIN. Try again.",
    recuperar: "Sign out and sign in again",
    erroRecuperacao: "We couldn't sign you out. Try again.",
    statusIndisponivel:
      "We couldn't confirm the lock status. Your content remains protected.",
    tentarNovamente: "Try again",
  },

  nav: {
    organizacao: "Organization",
    plataforma: "Platform",
    microsoft365: "Microsoft 365",
    galaxie: "Galaxie",
    copilot: "M365 Copilot",
    comms: "Comms",
    astro: "Astro",
    pulsar: "Pulsar",
    windows: "Windows",
    outlook: "Outlook",
    onedrive: "OneDrive",
    apps: "Apps",
    controlRoom: "Bridge",
    navegador: "Navigator",
    performance: "Performance",
    caminhosLongos: "Long paths",
    configuracoes: "Settings",
    conta: "Account",
    // Agenda lives at the bottom of the sidebar, a section apart from the inbox (#50).
    agenda: "Agenda",
    irPara365: "Go to Microsoft 365",
    sharepoint: "SharePoint",
    sair: "Sign out",
    alternarMenu: "Toggle sidebar",
    buscarEm: "Search in {nome}...",
  },

  abas: {
    bibliotecas: "Online libraries",
    meusArquivos: "My files",
    problemas: "Troubleshooting",
  },

  bibliotecas: {
    titulo: "Document library",
    descricao:
      "Document libraries organize the whole company inventory across SharePoint sites. Use this section to sync your OneDrive with the libraries you have access to.",
    descricaoPadrao: "SharePoint document library.",
    rodape:
      "Libraries show up in your OneDrive, in File Explorer. They only take up space when you open a file.",
    carregando: "Loading your libraries...",
    vazio: "No libraries available for your account.",
    conectado: "Connected",
    desconectado: "Disconnected",
    semAcesso: "No access",
    abrir: "Open library",
    abrirExplorer: "Open in File Explorer",
    abrirSharepoint: "Open in SharePoint",
    conectar: "Connect {nome}",
    desconectar: "Disconnect {nome}",
    tamanho: "Library size",
    pastas: "{n} folders",
    arquivos: "{n} files",
    tituloPastas: "Folders (approximate, from SharePoint search)",
    tituloArquivos: "Files (approximate, from SharePoint search)",
    consultando: "{o} — checking",
  },

  confirmar: {
    tituloConectar: "Before you continue",
    tituloDesconectar: "Remove this library?",
    descConectar:
      "Turning on {nome} makes OneDrive sync every folder and file in it to your machine. They show up in File Explorer, but only take up space once you open them.",
    descDesconectar:
      "The {nome} folder leaves your OneDrive and File Explorer, including files you downloaded for offline use. Nothing is deleted from SharePoint: the library stays there and you can reconnect whenever you want.",
    cartaoPastas: "Folders",
    cartaoArquivos: "Files",
    cartaoPeso: "Size",
    pastasConectar: "Number of folders in the library",
    pastasDesconectar: "Folders leaving your File Explorer",
    arquivosConectar: "Number of files in the library",
    arquivosDesconectar: "Files leaving your File Explorer",
    pesoDescricao: "Library size in the cloud",
    naoPerguntar: "Don't ask for confirmation again",
    naoPerguntarAjuda:
      "Next time, the library connects straight away when you flip the switch. You can turn the warning back on in Settings.",
    naoPerguntarAjudaRotulo:
      "More information about not asking for confirmation again",
    continuar: "Continue",
    depois: "Maybe later",
    remover: "Remove library",
    removendo: "Removing",
    removida: "Removed",
    cancelar: "Cancel",
  },

  problemas: {
    titulo: "Troubleshooting",
    descricao: "Fixes for the classic OneDrive headaches, without filing a ticket.",
    item1: "Restart OneDrive",
    item2: "Unstick syncing",
    item3: "Reconnect the Microsoft 365 account",
    item4: "Free up space with files on-demand",
  },

  emBreveOutlook: {
    descricao: "Email diagnostic tools will show up here.",
    item1: "Check rules and forwarding",
    item2: "Mailbox size and cleanup",
    item3: "Repair the Outlook profile",
  },

  emBrevePerformance: {
    descricao: "Diagnostics and performance tuning for this machine.",
    item1: "Disk space and temporary files",
    item2: "Programs that start with Windows",
    item3: "OneDrive sync status",
  },

  configuracoes: {
    descricao: "App and account preferences.",
  },

  notificacoes: {
    titulo: "Notifications",
    subtitulo: "Pick a sound for each kind of Bridge alert.",
    emailTitulo: "Received emails",
    emailDescricao: "Plays once when new emails arrive in your Inbox.",
    mensagemTitulo: "Received messages",
    mensagemDescricao: "Plays when you get a new chat message.",
    sincronizacaoTitulo: "Sync problems",
    sincronizacaoDescricao:
      "Plays when Bridge hits an error syncing with Microsoft 365.",
    semSom: "Do not play a thing",
    sonsDisponiveis: "Available sounds",
    preview: "Preview",
  },

  templates: {
    titulo: "Email templates",
    descricao:
      "Reusable models you can drop into a message body. They are kept on this computer.",
    novo: "New template",
    vazio:
      "No templates yet. Create one to reuse the texts you send all the time.",
    nome: "Name",
    nomePlaceholder: "e.g. Standard support reply",
    corpo: "Body",
    corpoPlaceholder: "Write the template content...",
    novoTitulo: "New template",
    editarTitulo: "Edit template",
    salvar: "Save",
    cancelar: "Cancel",
    editar: "Edit",
    excluir: "Delete",
    excluirTitulo: "Delete template?",
    excluirDescricao:
      "The template “{nome}” will be removed from this computer. This can't be undone.",
    salvo: "Template saved",
    excluido: "Template deleted",
    inserir: "Insert template",
    semTemplates: "No saved templates",
  },

  apps: {
    maisUsados: "Most used",
    explorar: "Explore by category",
    abrirAqui: "Open here",
    abrirNavegador: "Open in default browser",
    maisOpcoes: "More options",
    produtividade: "Productivity",
    utilitarios: "Utilities",
    educacao: "Education",
    comunicacao: "Communication",
    conteudo: "Content management",
    projetos: "Project management",
    experiencia: "Employee Experience",
    desenvolvimento: "Developer tools",
    avisoSessao:
      "Apps open right here. The first time, Microsoft asks you to sign in inside this window; after that the session is kept.",
  },

  meusArquivos: {
    titulo: "My files",
    descricao:
      "The folders in your personal OneDrive. Size, folders and files of each — to find what's eating space.",
    carregando: "Loading your folders...",
    vazio: "No folders in your OneDrive.",
    usoTitulo: "OneDrive usage",
    usoLinha: "{u} of {t}",
    usado: "Used",
    limite: "Limit",
    tiposTitulo: "Most common file types",
    tiposNota: "By count — Graph doesn't give size per type.",
    tiposUnidade: "{n} files",
  },

  navegador: {
    titulo: "Navigator",
    subtitulo: "Time to set sail",
    buscar: "Search apps or set a course...",
    vazio: "Nothing here.",
    navegar: "Set a course",
    irPara: "Go to {nome}",
    pesquisar: "Search the web for “{q}”",
    novaAba: "New tab",
    fecharAba: "Close tab",
    fecharOutras: "Close other tabs",
    abas: "Navigator tabs",
    dormindoClique: "{nome}: sleeping — click to reactivate",
    fixadaNome: "{nome}: pinned tab",
    dormindoTotal: "{n} sleeping",
    reativando: "Reactivating…",
    fixarAba: "Pin tab",
    desafixarAba: "Unpin tab",
    manterAcordada: "Keep awake",
    manterAcordadaAtivo: "Kept awake",
    permitirDormir: "Allow automatic sleeping",
    colocarDormir: "Put to sleep",
    dormirOutras: "Sleep other tabs",
    paleta: "Command palette",
    paletaTitulo: "Command palette",
    paletaDescricao: "Search tabs, apps and actions, or set a course.",
    paletaBuscar:
      "Tabs, apps, actions… or set a course  ( > actions · @ tabs · # history )",
    grupoAcoes: "Actions",
    grupoAbas: "Open tabs",
    grupoHistorico: "History",
    historicoEmBreve: "History is coming soon.",
    grupoMaisAcessados: "Most visited",
    historicoTitulo: "History",
    historicoBuscar: "Search history…",
    historicoVazio: "No pages in your history yet.",
    limparHistorico: "Clear history",
    limparUltimaHora: "Last hour",
    limparHoje: "Today",
    limparTudo: "Everything",
    modoPrivado: "Private mode",
    modoPrivadoAtivo: "Private browsing",
    abaPrivada: "{nome}: private tab",
    abaAtual: "Current",
    dormindo: "Sleeping",
    grupoNovo: "New group",
    grupoAdicionarA: "Add to group",
    grupoRemoverDe: "Remove from group",
    grupoRecolher: "Collapse group",
    grupoExpandir: "Expand group",
    grupoEditar: "Edit group",
    grupoExcluir: "Delete group",
    grupoNomeLabel: "Name",
    grupoCorLabel: "Color",
    grupoSalvar: "Save",
    grupoCancelar: "Cancel",
    grupoNomePadrao: "Group",
    grupoNomePlaceholder: "Group name",
    grupoReordenar: "Drag to reorder",
    grupoAria: "{nome}: tab group ({n})",
    corRosa: "Pink",
    corVioleta: "Violet",
    corVerde: "Green",
    corAmbar: "Amber",
    corVermelho: "Red",
    grupoFavoritos: "Favorites",
    favoritosBarra: "Favorites bar",
    favMenu: "Favorites",
    favAdicionarAba: "Add current tab",
    favNovaPasta: "New folder",
    favImportar: "Import from Chrome/Edge",
    favImportarDica: "Import your favorites from Chrome or Edge",
    favAbrir: "Open",
    favRenomear: "Rename",
    favRemover: "Remove",
    favNomeLabel: "Name",
    favSalvar: "Save",
    favCancelar: "Cancel",
    favPastaNomePadrao: "New folder",
    favRenomearTitulo: "Rename favorite",
    importarTitulo: "Import favorites",
    importarDescricao: "Choose which Chrome/Edge favorites to bring in.",
    importarCarregando: "Looking for favorites…",
    importarVazio: "No favorites found. Chrome or Edge not detected.",
    importarBloqueado:
      "We couldn't read your Chrome/Edge favorites — access may be blocked by your antivirus or security policy. Import from a file exported by the browser instead:",
    importarSemFavoritos: "No favorites found in Chrome/Edge.",
    importarArquivo: "Import from HTML file…",
    importarArquivoDica:
      "In Chrome/Edge: Favorites → Manage favorites → ⋯ → Export favorites.",
    importarSelecionarTudo: "Select all",
    importarLimpar: "Clear",
    importarContagem: "{n} of {total} selected",
    importarPerfil: "{navegador} · {perfil}",
    importarAplicar: "Import {n}",
    importarNada: "Nothing selected",
  },

  // Window controls (barra-janela.tsx). Only exist inside Tauri.
  janela: {
    minimizar: "Minimize",
    maximizar: "Maximize",
    restaurar: "Restore",
    fechar: "Close",
  },

  atualizacao: {
    titulo: "Update available!",
    versao: "Version {v} ({d})",
    descricao:
      "A new version of the app is ready. Updating now restarts the app and brings the latest fixes.",
    baixando: "Downloading the update... {p}%",
    agora: "Update now",
    atualizando: "Updating",
    depois: "Remind me later",
  },

  controlRoom: {
    saudacao: "Hi, {nome}",
    subtitulo: "Your day at a glance.",
    hoje: "Today",
    // Cliente de e-mail
    novoEmail: "New Mail",
    composeOutlook: "Compose in Outlook",
    composerEmBreve: "In-app composer coming soon — use \"Compose in Outlook\".",
    grupoMail: "Mail",
    grupoOutras: "Folders",
    pastaInbox: "Inbox",
    pastaDrafts: "Drafts",
    pastaSent: "Sent",
    pastaArchive: "Archive",
    pastaJunk: "Junk",
    pastaTrash: "Deleted",
    abaAnexos: "Files",
    semMensagens: "No messages in this folder.",
    semMensagensTitulo: "All clear",
    semResultados: "No results.",
    escolhaEmail: "Choose an email to view details.",
    ccLabel: "Cc",
    semEventosTitulo: "No events",
    agendaErroTitulo: "Couldn't load the calendar",
    agendaErroDica: "Temporary connection glitch. Try refreshing.",
    atualizar: "Refresh",
    tentarNovamente: "Try again",
    // Ações de e-mail
    excluir: "Delete",
    sinalizar: "Flag",
    marcarNaoLido: "Mark as unread",
    marcarLido: "Mark as read",
    removerSinal: "Unflag",
    excluirPermanente: "Delete permanently",
    esvaziarLixeira: "Empty trash",
    emailExcluido: "Email deleted.",
    erroAcao: "Couldn't complete the action.",
    // Menu de contexto de PASTA (#89)
    marcarTodasLidas: "Mark all as read",
    esvaziarPasta: "Empty folder",
    marcandoTodasLidas: "Marking all as read…",
    todasMarcadasLidas: "{n} marked as read.",
    nenhumaNaoLida: "No unread messages in this folder.",
    esvaziandoPasta: "Emptying the folder…",
    pastaEsvaziada: "Folder emptied ({n}).",
    esvaziarPastaTitulo: "Empty “{pasta}”?",
    esvaziarPastaDesc:
      "Every message in this folder will be deleted. This action can't be undone.",
    esvaziarPastaConfirmar: "Empty",
    // Move to folder (context menu submenu, #88)
    moverPara: "Move to folder…",
    moverBuscarPasta: "Search folders…",
    moverSemPastas: "No folders found.",
    moverCarregandoPastas: "Loading folders…",
    emailMovido: "Email moved to {pasta}.",
    selecionadosMovidos: "{n} emails moved to {pasta}.",
    // Subfolder CRUD (#90)
    criarSubpasta: "Create subfolder",
    renomearPasta: "Rename",
    excluirPasta: "Delete folder",
    moverPasta: "Move folder…",
    criarSubpastaTitulo: "New subfolder in “{pasta}”",
    criarSubpastaDesc: "Type the subfolder name.",
    renomearPastaTitulo: "Rename “{pasta}”",
    renomearPastaDesc: "Type the new folder name.",
    nomePastaRotulo: "Folder name",
    nomePastaPlaceholder: "e.g. Clients",
    nomePastaVazio: "Type a name for the folder.",
    nomePastaDuplicado: "A folder with this name already exists here.",
    criar: "Create",
    salvar: "Save",
    criandoSubpasta: "Creating the subfolder…",
    subpastaCriada: "Subfolder “{pasta}” created.",
    renomeandoPasta: "Renaming the folder…",
    pastaRenomeada: "Folder renamed to “{pasta}”.",
    excluirPastaTitulo: "Delete “{pasta}”?",
    excluirPastaDesc:
      "The folder and all its contents go to the Trash. You can restore them from there.",
    excluirPastaConfirmar: "Delete",
    excluindoPasta: "Deleting the folder…",
    pastaExcluida: "Folder “{pasta}” moved to Trash.",
    pastaExcluidaDefinitiva: "Folder “{pasta}” permanently deleted.",
    movendoPasta: "Moving the folder…",
    pastaMovida: "Folder moved to {pasta}.",
    // Toasts
    enviadoDescricao: "Your message was delivered.",
    envioPendente: "Sending in {n}s",
    envioPendenteDescricao: "Your message is waiting in Outbox.",
    desfazerEnvio: "Undo",
    envioCancelado: "Send canceled",
    enviandoAgora: "Sending message…",
    flagAdicionada: "Email flagged",
    flagRemovida: "Flag removed",
    downloadTitulo: "Download complete",
    baixandoAnexo: "Downloading attachment...",
    abrirArquivo: "Open",
    abrirPasta: "Open folder",
    expandirPasta: "Expand {pasta}",
    recolherPasta: "Collapse {pasta}",
    dispensar: "Dismiss",
    novoEmailRecebido: "New email",
    nSelecionados: "{n} selected",
    excluirSelecionados: "Delete selected",
    excluindo: "Deleting…",
    excluidos: "Deleted",
    mensagemOriginal: "Original message",
    ordenarPor: "Sort by",
    ordenaData: "Date",
    ordenaRemetente: "From",
    ordenaAssunto: "Subject",
    ordenaTamanho: "Size",
    ordenaImportancia: "Importance",
    ordenaFlag: "Flag",
    ordemDecrescente: "Descending",
    ordemCrescente: "Ascending",
    // Preferências de leitura (#95) — quando marcar a mensagem aberta como lida.
    // Namespace próprio (pref*) pra não colidir com as AÇÕES marcarLido/marcarNaoLido.
    prefLeitura: "Reading preferences",
    prefMarcarLidoTitulo: "Mark as read",
    prefMarcarLidoImediato: "When opened",
    prefMarcarLidoAtraso: "After {n} seconds",
    prefMarcarLidoManual: "Manually only",
    grupoFlagged: "Flagged",
    grupoHoje: "Today",
    grupoOntem: "Yesterday",
    grupo7dias: "Last 7 days",
    grupo30dias: "Last 30 days",
    grupoAntigos: "Older",
    expandirConversa: "Expand conversation",
    recolherConversa: "Collapse conversation",
    expandirConversaContagem: "Expand conversation ({n} messages)",
    nMensagensConversa: "{n} messages in this conversation",
    limparSelecao: "Clear selection",
    selecionarTudo: "Select all",
    selecionadosExcluidos: "{n} emails deleted.",
    conversaSelecionada: "1 conversation selected",
    conversasSelecionadas: "{n} conversations selected",
    multiSelecaoDica: "Del deletes selected · Ctrl+A selects all · Esc clears · ? shows shortcuts.",
    // Compose (new message modal + reply/forward)
    novaMensagem: "New message",
    ccoLabel: "Bcc",
    assunto: "Subject",
    assuntoPlaceholder: "Subject",
    corpoPlaceholder: "Write your message...",
    mostrarCcCco: "Cc/Bcc",
    contatosSalvos: "{n} contacts saved.",
    // Recipient autocomplete (#40)
    destinatariosPlaceholder: "Add recipients...",
    secaoSeusContatos: "Your contacts",
    secaoOrganizacao: "From your organization",
    secaoDigitado: "Use the address you typed",
    semContatos: "No contacts found.",
    buscandoContatos: "Searching contacts...",
    removerDestinatario: "Remove {nome}",
    // Mention @ in the body (#106)
    semDestinatariosMencao: "Add recipients in To/Cc/Bcc to mention them.",
    // Agenda / Up Next
    upNext: "Up Next",
    semEventos: "Nothing on the agenda this day.",
    agendaBuscar: "Search events...",
    online: "Online",
    diaInteiro: "All day",
    mailboxTitulo: "Mailbox",
    agendaTitulo: "Agenda",
    // Bridge header subtitles per module (#231)
    mailboxSubtitulo: "Your messages at a glance.",
    peopleSubtitulo: "Your Microsoft 365 contacts.",
    agendaSubtitulo: "Your upcoming schedule.",
    // Agenda — full calendar (#211)
    agendaNovoEvento: "New event",
    agendaHoje: "Today",
    agendaViewMes: "Month",
    agendaViewSemana: "Week",
    agendaViewDia: "Day",
    agendaViewAgenda: "Agenda",
    agendaCalSemEventos: "No events",
    agendaCalCarregando: "Loading events",
    agendaCalMais: "more",
    agendaEditar: "Edit",
    agendaExcluir: "Delete",
    agendaFormCriarTitulo: "New event",
    agendaFormEditarTitulo: "Edit event",
    agendaFormTitulo: "Title",
    agendaFormTituloPlaceholder: "Add a title",
    agendaFormDiaInteiro: "All day",
    agendaFormInicio: "Start",
    agendaFormFim: "End",
    agendaFormLocal: "Location",
    agendaFormCategoria: "Category",
    agendaFormSemCategoria: "None",
    agendaFormSalvar: "Save",
    agendaFormCriar: "Create",
    agendaFormCancelar: "Cancel",
    agendaTituloObrigatorio: "Enter a title for the event.",
    agendaCriado: "Event created.",
    agendaAtualizado: "Event updated.",
    agendaExcluido: "Event deleted.",
    agendaErroSalvar: "Couldn't save the event.",
    agendaErroExcluir: "Couldn't delete the event.",
    agendaFormConvidados: "Attendees",
    agendaFormConvidadosPlaceholder: "Add attendees",
    agendaFormTeams: "Teams meeting",
    agendaFormNovaCategoria: "New category",
    agendaFormNovaCategoriaNome: "Category name",
    agendaFormCriarCategoria: "Create",
    agendaCategoriaCriada: "Category created.",
    agendaCategoriaErro: "Couldn't create the category.",
    // Calendar selector (#233)
    agendaCalendarios: "Calendars",
    agendaCalendariosTodos: "All calendars",
    agendaCalendariosNenhum: "No calendars",
    agendaCalendariosContagem: "{n} calendars",
    agendaCalendariosVazio: "No calendars found.",
    agendaCalendariosErro: "Couldn't load calendars.",
    agendaCalendariosCarregando: "Loading calendars",
    agendaFormCalendario: "Calendar",
    peopleTitulo: "Contacts",
    peopleDescricao: "Your contacts and relevant people from Microsoft 365.",
    peopleContactsTab: "People",
    peopleOrganizationsTab: "Organizations",
    orgsDescricao: "Group contacts by domain and keep manual overrides.",
    orgsBuscar: "Search organizations...",
    orgsNova: "New organization",
    orgsVazia: "No organizations yet",
    orgsVaziaDesc: "Create an organization to group your contacts.",
    orgsSelecionar: "Select an organization",
    orgsSelecionarDesc: "View the organization's members, domains, and details.",
    orgsMembros: "{n} members",
    orgsAtribuir: "Assign contacts",
    orgsEditar: "Edit organization",
    orgsAbrirSite: "Open website",
    orgsDetalhes: "Details",
    orgsDominios: "Domains",
    orgsDominiosTooltip:
      "Optional — People whose domains are listed here will be added to this organization automatically. Press Enter or ; to enter more than one domain. Leave this blank to avoid linking domains to this organization.",
    orgsWebsite: "Website",
    orgsNotas: "Notes",
    orgsSemDado: "Not provided",
    orgsRemoverMembro: "Remove from organization",
    orgsCriarTitulo: "Create organization",
    orgsEditarTitulo: "Edit organization",
    orgsNome: "Name",
    orgsNomePlaceholder: "E.g. Galaxie Works",
    orgsDominiosPlaceholder: "galaxie.works, example.com",
    orgsDominiosAjuda:
      "Separate domains with commas or Enter. Leave blank for a manual list.",
    orgsCancelar: "Cancel",
    orgsSalvar: "Save",
    orgsCriar: "Create organization",
    orgsErroCampos: "Enter a name.",
    orgsAtribuirTitulo: "Assign contacts to {nome}",
    orgsBuscarContatos: "Search contacts...",
    orgsConfirmarAtribuicao: "Save assignments",
    orgsAtribuirContato: "Assign to organization",
    orgsSemOrganizacoes: "Create an organization first.",
    orgsCriada: "Organization created.",
    orgsAtualizada: "Organization updated.",
    orgsAtribuicoesSalvas: "Assignments saved.",
    orgsRedimensionar: "Resize organization list and detail",
    peopleBulkSelecionados: "{n} selected",
    peopleBulkLimpar: "Clear selection",
    peopleBulkAcoes: "Bulk actions",
    peopleBulkAtribuirOrg: "Assign to organization",
    bulkOrgTitulo: "Assign {n} contacts to an organization",
    bulkOrgDescricao:
      "Pick an existing organization or create a new one. The assignment is additive and removes no one.",
    bulkOrgBuscar: "Search organization...",
    bulkOrgSemOrgs: "No organizations yet.",
    bulkOrgCriarNova: "Create new organization…",
    bulkOrgVoltar: "Back",
    bulkOrgCriarContinuar: "Create and continue",
    bulkOrgConfirmar: "Confirm assignment",
    bulkOrgPreviewAlvo: "Assign to {nome}",
    bulkOrgPreviewAdicionados: "will be added",
    bulkOrgPreviewJaPertencem: "already belong (no change)",
    bulkOrgPreviewSemEmail: "without email join as explicit members",
    bulkOrgSucesso: "{n} contacts assigned to {nome}.",
    peopleBuscar: "Search by name, email, or company...",
    peopleOrdenar: "Sort contacts",
    peopleRelevancia: "Relevance",
    peopleAZ: "Name (A–Z)",
    peopleNome: "Name",
    peopleEmpresa: "Company",
    peopleCargo: "Role",
    peopleEmail: "Email",
    peopleTelefone: "Phone",
    peopleOrg: "Org",
    peopleExterno: "External",
    peopleFrequente: "Frequent",
    peopleContatos: "Contacts",
    peopleVoltar: "Back to contacts",
    peopleSelecionar: "Select a contact",
    peopleSelecionarDesc: "Choose someone from the list to see their details.",
    peopleVazio: "No contacts yet",
    peopleVazioDesc:
      "Your Outlook contacts will appear here as you email people.",
    peopleSemResultado: "No contacts match your search.",
    peopleLimparBusca: "Clear search",
    peopleErro: "We couldn't refresh every contact source.",
    peopleTentarNovamente: "Try again",
    peopleSemPermissao: "People access required",
    peopleSemPermissaoDesc:
      "Grant {escopos} to load your contacts. Sign-in only opens after you confirm.",
    peopleConcederAcesso: "Grant access",
    peopleCompor: "Compose email",
    peopleVerModulo: "View in People",
    peopleEmails: "Emails",
    peopleTelefones: "Phones",
    peopleEmpresaCargo: "Company and role",
    peopleSemDado: "Not provided",
    peopleEnrich: "Enrich",
    peopleEnrichPrompt: "Enrich this contact",
    peopleEnrichPromptDesc:
      "Empty fields can be filled with data from People and the directory.",
    peopleEnriching: "Enriching…",
    peopleEnrichPreview: "Review additions",
    peopleEnrichPreviewDesc:
      "Choose exactly which fields to apply. Nothing has been saved yet.",
    peopleEnrichApply: "Apply",
    peopleEnrichSessionApply: "Apply to this session",
    peopleEnrichCancel: "Cancel",
    peopleEnrichNoChanges: "No new data was found for this contact.",
    peopleEnrichSourceError: "A source did not respond",
    peopleEnrichReadOnly: "Session only",
    peopleEnrichReadOnlyDesc:
      "The current sign-in needs Contacts.ReadWrite to save. The app will not request consent or attempt a write without your action.",
    peopleEnrichCopy: "Copy data",
    peopleEnrichCopied: "Data copied",
    peopleEnrichSaved: "Contact enriched",
    peopleEnrichSessionSaved: "Data applied to this session only",
    peopleEnrichError: "This contact could not be enriched.",
    peopleSourceContacts: "Contacts",
    peopleSourcePeople: "People",
    peopleSourceDirectory: "Directory",
    peopleFilterSourceContacts: "Saved contacts",
    peopleFilterSourcePeople: "Relevant people",
    peopleFilterSourceDirectory: "Organization directory",
    peopleSource: "Source",
    peopleRelationship: "Relationship",
    peopleHasPhone: "Has phone",
    peopleYes: "Yes",
    peopleNo: "No",
    peopleFilters: "Filters",
    peopleClearFilters: "Clear filters",
    peopleColumns: "Columns",
    peopleTableView: "Table view",
    peopleCardsView: "Cards view",
    peopleRowActions: "Contact actions",
    peopleCopyEmail: "Copy email",
    peopleEmailCopied: "Email copied",
    peopleLoadMore: "Load more",
    peopleDepartment: "Department",
    peopleOfficeLocation: "Office location",
    peopleManager: "Manager",
    peopleFieldBusinessPhone: "Business phone",
    peopleFieldMobilePhone: "Mobile phone",
    peopleFieldPhoto: "Photo",
    peopleEdit: "Edit contact",
    peopleSave: "Save",
    peopleSaving: "Saving…",
    peopleEditUnavailable: "Editing unavailable",
    peopleEditUnavailableDesc:
      "This contact cannot be edited right now.",
    peopleEditDirectoryTitle: "This is not a saved contact",
    peopleEditDirectoryDesc:
      "This person is not saved in your contacts yet, so they cannot be edited here.",
    peopleEditDirectoryTooltip:
      "Information about users in your organization can only be changed by an administrator.",
    peopleEditError: "The contact could not be saved. Previous values were restored.",
    peopleInvalidEmail: "Review the email addresses.",
    peopleInvalidPhone: "Review the phone numbers.",
    peopleInteractions: "Recent interactions",
    peopleInteractionsEmpty: "No recent messages with this contact.",
    peopleInteractionsError: "Interactions could not be loaded.",
    peopleInbound: "Received",
    peopleOutbound: "Sent",
    peopleEnrichAll: "Enrich all",
    peopleEnrichSelected: "Enrich selected",
    peopleBulkTitle: "Enrichment review",
    peopleBulkContact: "Contact {atual} of {total}",
    peopleBulkSkip: "Skip",
    peopleBulkDone: "Review complete",
    colapsar: "Collapse",
    badgeMeeting: "Meeting",
    badgeEvent: "Event",
    convidados: "{n} attendees",
    umConvidado: "1 attendee",
    arquivos: "{n} files",
    umArquivo: "1 file",
    // Inbox do dia
    inbox: "Inbox",
    semEmailsDia: "No email on this day.",
    buscarEmail: "Search mail...",
    abaTodos: "All",
    abaNaoLidos: "Unread",
    abaSinalizados: "Flagged",
    filtroLabel: "Filter",
    filtroToMe: "To me",
    filtroMentions: "Mentions me",
    filtroInvites: "Calendar invites",
    filtroDe: "From",
    filtroDePlaceholder: "Sender...",
    filtroStatus: "Status",
    filtroLidos: "Read",
    filtroSim: "Yes",
    filtroNao: "No",
    filtroEscopo: "Scope",
    filtroBuscarCampo: "Search field...",
    filtroLimpar: "Clear",
    filtroGrupoBasico: "Basic",
    filtroGrupoSelecao: "Select",
    filtroOperadorIs: "is",
    filtroOpNaoE: "is not",
    filtroOpContem: "contains",
    filtroOpNaoContem: "doesn't contain",
    filtroSelecione: "Select...",
    // Date range filter (#110): "Date" field with DateSelector in a modal.
    filtroData: "Date",
    filtroDataSelecione: "Select a date",
    filtroDataTitulo: "Filter by date",
    filtroDataDescricao: "Choose a period to filter messages by date.",
    filtroDataDica: "Try: 2025, Q4, 05/10/2025",
    filtroAplicar: "Apply",
    // Detalhe do evento
    organizador: "Organizer",
    local: "Location",
    convidadosTitulo: "Attendees",
    entrarReuniao: "Join meeting",
    // Detalhe do e-mail
    para: "To",
    anexosTitulo: "Attachments",
    responder: "Reply",
    encaminhar: "Forward",
    // Keyboard shortcuts (#28) — catalog for the help modal ("?"). Flat keys.
    atalhosTitulo: "Keyboard shortcuts",
    atalhosDescricao: "Operate Bridge without the mouse.",
    atalhosCatNavegacao: "Navigation",
    atalhosCatSelecao: "Selection",
    atalhosCatAcoes: "Actions",
    atalhosCatGeral: "General",
    atalhosNavegar: "Move between messages",
    atalhosBuscar: "Search",
    atalhosSelecionarTudo: "Select all",
    atalhosIntervalo: "Select range",
    atalhosCliqueIntervalo: "Shift + click",
    atalhosMarcarItem: "Toggle message selection",
    atalhosLimpar: "Clear selection / search",
    atalhosResponder: "Reply",
    atalhosResponderTodos: "Reply all",
    atalhosEncaminhar: "Forward",
    atalhosCompor: "New message",
    atalhosLidoNaoLido: "Mark as read/unread",
    atalhosSinalizar: "Flag",
    atalhosExcluir: "Delete",
    atalhosAjuda: "Show this help",
    abrirOutlook: "Open in Outlook",
    semCorpo: "(no content)",
    conteudoAparado: "Show trimmed content",
    zoomResetar: "Reset zoom (Ctrl+0)",
    // Reader security (#91)
    segLinkTitulo: "Open external link?",
    segLinkDescricao: "Check the real destination before opening.",
    segLinkDestino: "Real destination",
    segLinkTexto: "Link text",
    segLinkAbrir: "Open anyway",
    segLinkCancelar: "Cancel",
    segLinkSuspeito: "Suspicious link",
    segLinkVerificado: "No risk signals detected.",
    segAvisoMismatch: "The link text looks like a different site than the real destination.",
    segAvisoEncurtador: "URL shortener — the final destination is hidden.",
    segAvisoIp: "The link points to an IP address, not a domain.",
    segAvisoPunycode: "Domain with international characters (spoofing risk).",
    segAvisoInseguro: "Insecure connection (HTTP).",
    segAvisoRedirecionamento: "The link embeds a redirect to another address.",
    segAutAutenticado: "Authenticated",
    segAutParcial: "Partial",
    segAutFalhou: "Authentication failed",
    segAutIndisponivel: "No data",
    segAutTooltipAutenticado:
      "Verified sender — this email passed the authentication checks (SPF, DKIM and DMARC).",
    segAutTooltipParcial:
      "Partial authentication — some checks didn't pass. Verify the sender before trusting it.",
    segAutTooltipFalhou:
      "Authentication failed — this email may not be from who it claims to be. Be careful with links and attachments.",
    segAutTooltipIndisponivel: "No authentication data for this email.",
    segAutDetalhesTecnicos: "Technical details",
    segReplyToTitulo: "Replies go to a different address",
    segReplyToDescricao:
      "When you reply, your message goes to {enderecos}, not to the sender ({de}). This is common in phishing — confirm before replying.",
    // Compose / envio
    responderTodos: "Reply all",
    paraPlaceholder: "To (comma-separated)",
    responderPlaceholder: "Write your reply...",
    encaminharPlaceholder: "Write a message...",
    enviarDe: "Send from",
    enviar: "Send",
    cancelar: "Cancel",
    enviado: "Email sent.",
    erroEnvio: "Couldn't send the email.",
    escrevaAlgo: "Write a message before sending.",
    informeDestino: "Enter at least one recipient.",
    // Sender insights (#94)
    insightsTitulo: "Sender insights",
    insightsAbrir: "View insights for {nome}",
    insightsErro: "Couldn't load insights.",
    insightsTentar: "Try again",
    insightsPrimeiroContato: "First email with this sender.",
    insightsRecebidos: "Received",
    insightsEnviados: "Sent",
    insightsPrimeiro: "First contact",
    insightsUltimo: "Last contact",
    insightsFrequencia: "Frequency",
    insightsPorMes: "~{n}/mo",
    // Shared mailboxes (#111)
    caixaMinha: "My mailbox",
    caixaSeletor: "Active mailbox",
    caixaAdicionarItem: "Add mailbox…",
    caixaDialogTitulo: "Add shared mailbox",
    caixaDialogDesc: "Enter the address of the shared mailbox you want to access.",
    caixaEnderecoRotulo: "Email address",
    caixaEnderecoPlaceholder: "e.g. finance@company.com",
    caixaEnderecoInvalido: "Enter a valid email address.",
    caixaJaAdicionada: "That mailbox is already in the selector.",
    caixaValidando: "Validating access…",
    caixaAdicionarConfirmar: "Add",
    caixaAdicionada: "Mailbox {addr} added.",
    caixaSemAcesso: "You don't have access to that mailbox.",
    caixaNaoEncontrada: "Address not found.",
    caixaErro: "Couldn't validate the mailbox.",
    caixaRelogin: "Sign in again to access shared mailboxes.",
    caixaCompartilhadaTitulo: "Shared mailbox",
    caixaCompartilhadaDesc: "Message reading and management are enabled.",
    caixaSomenteLeitura: "Read-only — available in your personal mailbox",
    caixaSemPermissaoEscrita:
      "You don't have permission to modify this shared mailbox.",
    caixaSemPermissaoEnvio:
      "You don't have permission to send using this shared mailbox.",
    caixaEnvioRelogin:
      "Sign in again to send using shared mailboxes.",
    caixaAcessoParcial:
      "Partial access — you don't have permission to open this folder.",
  },
  emBreveControlRoom: {
    descricao: "The Galaxie control panel — your overview. Coming soon.",
  },
  emBreveComms: {
    descricao: "Fast team chat. Coming soon.",
  },
  emBreveAstro: {
    descricao: "The Galaxie chatbot will live here. Coming soon.",
  },
  emBrevePulsar: {
    descricao: "Notifications and alerts — every pulse, a heads-up.",
  },

  caminhosLongos: {
    titulo: "Long paths",
    descricao:
      "By default Windows stops at 260 characters of path. Deeply nested project folders go past that and the file simply won't open — not in File Explorer, not in your apps.",
    verificando: "checking",
    ativado: "Enabled",
    desativado: "Disabled",
    aviso:
      "The change is made in the Windows registry and applies to the whole computer, so Windows will ask for administrator confirmation. Some programs only pick up the change after a restart.",
    nadaAFazer: "Nothing to do — this computer already accepts long paths.",
    ativar: "Enable long paths",
    aplicando: "Applying...",
  },

  tema: {
    alternar: "Toggle light and dark theme",
  },

  erro: {
    titulo: "Something went wrong",
    descricao:
      "The app hit an unexpected error. You can reload to try again.",
    recarregar: "Reload",
    detalhes: "Technical details",
  },
};

export const DICIONARIOS: Record<Idioma, Dicionario> = {
  "pt-BR": pt,
  en: en as Dicionario,
};
